project_id = "czknjslirxpzjipqxtid"

[functions.create-investment]
verify_jwt = true

[functions.chat]
verify_jwt = false

[functions.korapay-webhook]
verify_jwt = false

[functions.korapay-webhook-new]
verify_jwt = false

[functions.test-working]
verify_jwt = false

[functions.untested-create-investment]
verify_jwt = true
