// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://czknjslirxpzjipqxtid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6a25qc2xpcnhwemppcHF4dGlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NTA4ODIsImV4cCI6MjA3MjQyNjg4Mn0.__ph7qbVEh2z4Pf23GwnWMiP1uancMbzO3kGNZXk2FI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});